### PR TITLE
Switch to CentOS 8

### PR DESCRIPTION
**Pull request by bdunne**
~~Note: this would go from 10.15 down to 10.14 at the current time~~

Also, we should try to get to ubi8, so I'm not sure this step is necessary

### CODE REVIEW

**Comment by Fryguy** [comment]
@simaishi Thoughts?  I think I'd rather just get to ubi if possible

**Comment by simaishi** [comment]
We've always used an existing postgresql container image to be the base image (as opposed to using CentOS/UBI as the base). There is currently no UBI8 based postgresql image available, so it might be a good idea to move to CentOS 8 based postgresql first, then look into UBI 8 later.

**Comment by simaishi** [comment]
CentOS AppStream now has 10.15, so this will no longer be a downgrade. LGTM, assuming there is no other change neeeded due to going from SCL to non-SCL rpm.

**Comment by Fryguy** [comment]
@bdunne Should we un-wip?

**Comment by bdunne** [comment]
Yes, tested and removed the WIP.  This is ready to go.

**Pull request merged**
